version: 1.0.{build}
branches:
  only:
  - master
os: Windows Server 2012 R2
configuration: Release
platform: Any CPU
clone_depth: 1
before_build:
- cmd: nuget restore src\Plaid.sln
build:
  project: src/Plaid.sln
  verbosity: minimal
deploy: off
